### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by jabenninghoff**
Use upstream DESCRIPTION going forward.

### CODE REVIEW

**Comment by jto888** [comment]
Thanks for change. Sorry I am not skilled with github, but I am committing the width_initial fix separately.
Would appreciate understanding your use of FaultTree.

**Comment by jabenninghoff** [comment]
Oh, I sort of accidentally submitted it, but I'm glad it helped! I have more detail on what was failing here: https://jabenninghoff.github.io/rtraining/FaultTree.html

Thanks for merging the fix!

I'm using FaultTree at work, for analyzing software system reliability. It's pretty basic but I use R extensively and FaultTree was a nice way to show how availability of application components impacted overall system availability. I don't have anything public to share, but this work is similar:

https://www.usenix.org/conference/srecon19americas/presentation/falko

**Comment by jabenninghoff** [comment]
Also, the width_initial fix doesn't match my fix...

you have:

```r
var width_initial = $("dev").width()/2-60;
```

I have:

```r
var width_initial = $("div").width()/2-60;
```

The "dev" should be "div"

**Comment by jto888** [comment]
Got it, I have noticed this improves rendering to html with rmarkdown. I will post as version 0.2.8.3. R-forge has been down for last day or so. I get very little feed back on this package, so it is always refreshing to get some comment. I am thinking of posting this to CRAN. I like keeping it separate from FaultTree itself due to extra dependencies.

I tried a couple of years ago to advance the D3 library from current v3 but could not maintain all functionality, so abandoned. Any ideas here?
Perhaps we could move discussion to email dsilk@openreliabililty.org

**Pull request closed without merging**
